version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    ### RabbitMQ ###
    rabbitmq:
        build: ./rabbitmq
        ports:
            - "${RABBITMQ_HOST_PORT}:5672"
            - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
            - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
        privileged: true
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        volumes:
            - $PWD/rabbitmq/data:/var/lib/rabbitmq
        networks:
            - sail
networks:
    sail:
        driver: bridge
